### ISSUE TITLE
Filename or extension too long (OSError) on Windows

### ISSUE THREAD

**Issue by abhidg** [carpentriesoffline/offlinedatasci#119]
From @jsteyn - creating a venv and installing inside it fixes the issue

**Comment by ethanwhite** [comment]
Thanks @abhidg & @jsteyn. We aren't seeing this in our Windows tests (or on our local Windows machine) so we'll need some more detail in order to explore it.

**Comment by ethanwhite** [comment]
The large number of nest directories `\\lib\\build\\lib\\build\\lib\\build...` is really weird. Is this behavior exclusive to `offlinedatasci` or does it happen with other packages?

**Comment by hturner** [comment]
It does seem to be specific to `offlinedatasci`. E.g. `pip install rptree` and `py -m pip install codetiming` both work fine, but equivalent commands for `offlinedatasci` give above error, unless in a virtual environment.

Maybe related to https://github.com/pypa/setuptools/issues/4076?

**Comment by ethanwhite** [comment]
Thanks @hturner! That's super helpful. Based on that I'm guessing that this was an issue with repeated local builds as part of the testing effort. If that's right the #126 should fix the issue. Can you checkout that PR and see if that fixes things for you.

Since I just had to look this up again yesterday for the 42nd time here's how to checkout the PR:

```sh
git fetch upstream pull/126/head:test-branch
git switch test-branch
```

**Comment by ethanwhite** [comment]
Reopening since we still need someone to confirm that the fixed worked. The fix has now been merged into main so reinstalling from main is all we need for a test.

**Comment by hturner** [comment]
Reinstalling from main with `pip install git+https://git@github.com/carpentriesoffline/offlinedatasci.git` works for me.
